# Generated by Django 2.2.11 on 2020-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='title_eng',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
