# Generated by Django 2.2.11 on 2020-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200413_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialcomplete',
            name='myshows_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seriallater',
            name='myshows_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
