# Generated by Django 2.2.11 on 2020-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200425_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialcomplete',
            name='rating',
            field=models.CharField(default='Нет', max_length=50),
        ),
    ]
