# Generated by Django 2.2.11 on 2020-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200614_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialcomplete',
            name='title_eng',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seriallater',
            name='title_eng',
            field=models.CharField(max_length=50),
        ),
    ]
