# Generated by Django 2.2.11 on 2021-07-10 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0010_auto_20210505_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialcomplete',
            name='user_link',
        ),
        migrations.AddField(
            model_name='serialcomplete',
            name='user_link',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='seriallater',
            name='user_link',
        ),
        migrations.AddField(
            model_name='seriallater',
            name='user_link',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
